### ISSUE TITLE
Alter intensity/resolution of a shader?

### ISSUE THREAD

**Issue by benjistiles** [DaveyL2013/secrets-no-more#5]
Love the mod, great job btw.
Is there a way to alter the intensity or resolution of a specific shader overlay? For example, the 'bits' shader is too low resolution to be playable. I tried changing the resolution in the Minecraft.jar assets/minecraft/shaders/post and /program. It was set to 4.0 as default and I tried changing it to 16.0 in the files (same as creeper overlay), but it didn't seem to work. I saw in SecrNoMore.class that the shaders were pulled from that location, so this might be more of a Minecraft issue than your mod, but I wasn't sure.
Completely understandable if this isn't important or doable lol, just trying to get a playable old-school look.
Thanks!

**Comment by DaveyL2013** [comment]
I can't properly look into this right now because yesterday a storm killed internet and the cell towers near my house, but I'm pretty sure you should be able to change it with a resource pack. If that works, you can just close the issue, if not I will try to get it working when I get internet back because I actively tried to make sure it worked for custom shaders.

**Comment by benjistiles** [comment]
That worked, thanks!
